name: build-portable-conda

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml      # creates env from your file
          environment-name: pyenv                # must match name you want
          init-shell: powershell                 # valid values include 'powershell'
          generate-run-shell: true               # make subsequent steps auto-use the env
          cache-downloads: true
          cache-environment: true

      - name: Show Python (should be env python)
        shell: powershell
        run: |
          python -V
          where python

      - name: Install conda-pack inside env
        shell: powershell
        run: |
          python -m pip install --no-input conda-pack

      - name: Pack environment to pyenv.zip
        shell: powershell
        run: |
          python -m conda_pack -o pyenv.zip -v

      - name: Prepare bundle
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path bundle | Out-Null
          Expand-Archive -Path pyenv.zip -DestinationPath bundle\pyenv -Force
          New-Item -ItemType Directory -Force -Path bundle\app | Out-Null
          Copy-Item -Recurse app\* bundle\app\
          $bat = @'
          @echo off
          setlocal
          cd /d %~dp0
          if exist .\pyenv\Scripts\conda-unpack.exe (
            .\pyenv\Scripts\conda-unpack.exe
          )
          .\pyenv\python.exe .\app\main.py
          echo.
          echo Done. Press any key to exit.
          pause >nul
          '@
          Set-Content -Path bundle\RUN_ME.bat -Value $bat -Encoding ascii

      - name: Zip final bundle
        shell: powershell
        run: Compress-Archive -Path bundle\* -DestinationPath python_portable_win.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python_portable_win
          path: python_portable_win.zip
          if-no-files-found: error

